# Form implementation generated from reading ui file 'окно_входа.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QLineEdit


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(818, 700)
        MainWindow.setMaximumSize(QtCore.QSize(16777208, 16777215))
        MainWindow.setStyleSheet("background-color: #0a0a0a;")
        MainWindow.setIconSize(QtCore.QSize(40, 40))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(220, 150, 281, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label_2.setStyleSheet("color: white; font-family: Fjord One; font-size: 18px; font-weight: bold;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.input_logi = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        self.input_logi.setStyleSheet("background-color: #16213e; color: white; border: 2px solid #ff00ff; border-radius: 8px; padding: 10px;")
        self.input_logi.setObjectName("input_logi")
        self.horizontalLayout.addWidget(self.input_logi)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(220, 230, 281, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_2)
        self.label_3.setStyleSheet("color: white; font-family: Fjord One; font-size: 18px; font-weight: bold;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.input_pas = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_2)
        self.input_pas.setStyleSheet("background-color: #16213e; color: white; border: 2px solid #00ffff\n"
"; border-radius: 8px; padding: 10px;")
        self.input_pas.setObjectName("input_pas")
        self.input_pas.setEchoMode(QLineEdit.EchoMode.Password)
        self.horizontalLayout_2.addWidget(self.input_pas)
        self.toggle_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.toggle_button.setMaximumSize(QtCore.QSize(30, 30))
        self.toggle_button.setStyleSheet("color: white;\n"
"    background-color: transparent;\n"
"    border: 1px solid gray;\n"
"    border-radius: 6px;")
        self.toggle_button.setObjectName("toggle_button")
        self.toggle_button.setCheckable(True)
        self.horizontalLayout_2.addWidget(self.toggle_button)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(220, 310, 281, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ot_button = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.ot_button.setMinimumSize(QtCore.QSize(279, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ot_button.setFont(font)
        self.ot_button.setStyleSheet("background-color: #ff00ff\n"
"; color: white; border: none; border-radius: 8px; padding: 12px; font-weight: bold;")
        self.ot_button.setObjectName("ot_button")
        self.verticalLayout.addWidget(self.ot_button)
        self.log_button = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.log_button.setFont(font)
        self.log_button.setStyleSheet("background-color: #00ffff\n"
"\n"
"; color: white; border: none; border-radius: 8px; padding: 12px; font-weight: bold;")
        self.log_button.setObjectName("log_button")
        self.verticalLayout.addWidget(self.log_button)
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(220, 40, 281, 41))
        self.label_4.setStyleSheet("color: white; font-family: Fjord One; font-size: 18px; font-weight: bold;")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 818, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Логин</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Пароль</span></p></body></html>"))
        self.toggle_button.setText(_translate("MainWindow", "👁"))
        self.ot_button.setText(_translate("MainWindow", "Войти"))
        self.log_button.setText(_translate("MainWindow", "Зарегистрироваться"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Система конспектов</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
