# Form implementation generated from reading ui file 'окно_регистрации.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QLineEdit


class Ui_LogWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(787, 539)
        MainWindow.setMinimumSize(QtCore.QSize(400, 350))
        MainWindow.setStyleSheet("background-color: #0a0a0a;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(270, 50, 281, 41))
        self.label_4.setStyleSheet("color: white; font-family: Fjord One; font-size: 18px; font-weight: bold;")
        self.label_4.setObjectName("label_4")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(270, 140, 281, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label_8.setStyleSheet("color: white; font-family: Fjord One; font-size: 18px; font-weight: bold;")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.input_logr = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        self.input_logr.setStyleSheet("background-color: #16213e; color: white; border: 2px solid #ff00ff; border-radius: 8px; padding: 10px;")
        self.input_logr.setObjectName("input_logr")
        self.horizontalLayout_3.addWidget(self.input_logr)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(270, 220, 281, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_2)
        self.label_9.setStyleSheet("color: white; font-family: Fjord One; font-size: 18px; font-weight: bold;")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.input_pasr = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_2)
        self.input_pasr.setEchoMode(QLineEdit.EchoMode.Password)
        self.input_pasr.setStyleSheet("background-color: #16213e; color: white; border: 2px solid #00ffff\n"
"; border-radius: 8px; padding: 10px;")
        self.input_pasr.setObjectName("input_pasr")
        self.horizontalLayout_4.addWidget(self.input_pasr)
        self.toggle_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.toggle_button.setMaximumSize(QtCore.QSize(30, 30))
        self.toggle_button.setStyleSheet("color: white;\n"
"    background-color: transparent;\n"
"    border: 1px solid gray;\n"
"    border-radius: 6px;")
        self.toggle_button.setObjectName("toggle_button")
        self.horizontalLayout_4.addWidget(self.toggle_button)
        self.exit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(270, 450, 281, 37))
        self.exit_button.setMinimumSize(QtCore.QSize(279, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.exit_button.setFont(font)
        self.exit_button.setStyleSheet("background-color: #ff00ff\n"
"; color: white; border: none; border-radius: 8px; padding: 12px; font-weight: bold;")
        self.exit_button.setObjectName("exit_button")
        self.log_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.log_button.setGeometry(QtCore.QRect(270, 400, 281, 37))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.log_button.setFont(font)
        self.log_button.setStyleSheet("background-color: #00ffff\n"
"\n"
"; color: white; border: none; border-radius: 8px; padding: 12px; font-weight: bold;")
        self.log_button.setObjectName("log_button")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(270, 300, 281, 80))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_10 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_3)
        self.label_10.setStyleSheet("color: white; font-family: Fjord One; font-size: 18px; font-weight: bold;")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.input_pasr2 = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_3)
        self.input_pasr2.setStyleSheet("background-color: #16213e; color: white; border: 2px solid #ff00ff\n"
"; border-radius: 8px; padding: 10px;")
        self.input_pasr2.setObjectName("input_pasr2")
        self.input_pasr2.setEchoMode(QLineEdit.EchoMode.Password)
        self.horizontalLayout_5.addWidget(self.input_pasr2)
        self.toggle_button_2 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_3)
        self.toggle_button_2.setMaximumSize(QtCore.QSize(30, 30))
        self.toggle_button_2.setStyleSheet("color: white;\n"
"    background-color: transparent;\n"
"    border: 1px solid gray;\n"
"    border-radius: 6px;")
        self.toggle_button_2.setObjectName("toggle_button_2")
        self.horizontalLayout_5.addWidget(self.toggle_button_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 787, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Регистрация</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Логин</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Пароль</span></p></body></html>"))
        self.toggle_button.setText(_translate("MainWindow", "👁"))
        self.exit_button.setText(_translate("MainWindow", "Назад"))
        self.log_button.setText(_translate("MainWindow", "Зарегистрироваться"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Повторите</span></p><p align=\"center\"><span style=\" font-size:12pt;\">пароль</span></p></body></html>"))
        self.toggle_button_2.setText(_translate("MainWindow", "👁"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_LogWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
